import React, { useEffect, useMemo, useRef, useState } from "react";

const TOUR_TIMING = {
  firstMoveDelay: 2200,
  slideDuration: 13500,
  deepSlideDuration: 16000,
};

const slides = [
  {
    id: "ecosystem",
    title: "A Connected Food Ecosystem",
    subtitle: "People. Resources. Opportunity. Circulating Together.",
    image: "/EcosystemOverview.png",
    deep: true,
    ecosystem: true,
    text: "Bronson Family Farm is a place-based ecosystem where growers, families, youth, customers, partners, resources, and opportunities work together instead of separately. The ecosystem helps food, knowledge, workforce development, partnerships, and economic value circulate locally to strengthen the community over time.",
  },
  {
    id: "place",
    title: "The Place",
    subtitle: "Historic Lansdowne Airport • Youngstown, Ohio",
    image: "/SAM_0220.JPG",
    deep: true,
    text: "Bronson Family Farm is being developed on land connected to the Historic Lansdowne Airport. What was once a place of transportation and movement is now becoming a place of food production, learning, workforce development, agritourism, and community gathering.",
  },
  {
    id: "guest",
    title: "Explore the Farm",
    subtitle: "Experience the vision, story, and purpose",
    image: "/SAM_0221.JPG",
    pathway: "Explore the Farm",
    text: "Guests enter the ecosystem to understand what Bronson Family Farm is becoming and why it matters. They experience the land, the story, the growing areas, the community purpose, and the vision for food access, education, and family-centered agritourism.",
    detail: "This experience helps visitors understand the full vision before they decide how they want to participate.",
    experience: [
      "See the farm story, history, and purpose.",
      "Understand what a community food ecosystem is.",
      "Explore growing areas, demonstrations, and future destination plans.",
      "Identify where they may fit as a visitor, customer, volunteer, partner, or supporter.",
    ],
  },
  {
    id: "customer",
    title: "Healthy Food Access",
    subtitle: "Fresh, chemical-free food and healthier choices",
    image: "/SAM_0222.JPG",
    pathway: "Healthy Food Access",
    text: "Families connect to fresh, chemical-free food grown locally with care. This experience supports healthier family choices, nutrition awareness, and repeat access to local food through the marketplace and future distribution system.",
    detail: "This experience connects families to food, nutrition, wellness, and consistent healthy choices.",
    experience: [
      "Learn what is being grown and why quality matters.",
      "Connect to fresh, chemical-free produce.",
      "Understand how local food supports health and family wellness.",
      "Return through marketplace access, ordering, events, and community food distribution.",
    ],
  },
  {
    id: "marketplace",
    title: "Community Marketplace",
    subtitle: "Food and money circulate locally",
    image: "/SAM_0223.JPG",
    deep: true,
    pathway: "Community Marketplace",
    text: "The Community Marketplace helps food move efficiently through the ecosystem. Growers should not have to carry the burden of distribution alone. Bronson Family Farm works to connect growers with customers, schools, markets, businesses, organizations, institutions, and community buyers so the food moves — not the farmer.",
    detail: "This experience turns interest into purchasing power, distribution, and sustainability.",
    experience: [
      "Connect local growers to buyers and community outlets.",
      "Support food movement to schools, families, businesses, and organizations.",
      "Create a stronger system for selling, ordering, pickup, and distribution.",
      "Keep food dollars circulating locally instead of leaving the community.",
    ],
  },
  {
    id: "grower",
    title: "Grower Support System",
    subtitle: "Tools, supplies, demonstrations, and support",
    image: "/SAM_0225.JPG",
    deep: true,
    pathway: "Grower Support System",
    text: "Growers need more than land. They need education, demonstrations, tools, infrastructure ideas, networking, market access, and support. The Growers Supply Market was created to help small farms, gardeners, and community growers learn, prepare, build confidence, and grow more successfully.",
    detail: "This experience connects producers to tools, knowledge, market participation, and opportunity.",
    experience: [
      "See demonstrations and growing methods.",
      "Learn about tools, supplies, soil, irrigation, and production needs.",
      "Connect to marketplace and distribution opportunities.",
      "Build confidence as part of a larger food ecosystem.",
    ],
  },
  {
    id: "youth",
    title: "Youth Workforce Development",
    subtitle: "Skills, leadership, and future readiness",
    image: "/SAM_0226.JPG",
    deep: true,
    pathway: "Youth Workforce Development",
    text: "Youth workforce development is built into the ecosystem. Young people gain hands-on experience in leadership, responsibility, communication, teamwork, agriculture, food handling, customer engagement, and outdoor work readiness.",
    detail: "This experience builds responsibility, practical skills, confidence, and future readiness.",
    experience: [
      "Participate in structured outdoor learning and work experiences.",
      "Practice responsibility, safety, teamwork, and communication.",
      "Learn growing, food handling, customer service, and leadership skills.",
      "Build confidence for future employment, entrepreneurship, and service.",
    ],
  },
  {
    id: "partners",
    title: "Community Partnerships",
    subtitle: "Shared impact and collaboration",
    image: "/SAM_0229.JPG",
    pathway: "Community Partnerships",
    text: "Partners strengthen the ecosystem through collaboration, education, workforce support, health programming, demonstrations, funding, tools, sponsorship, and shared community investment.",
    detail: "This experience aligns resources, collaboration, and community benefit.",
    experience: [
      "Identify where partner resources can strengthen the ecosystem.",
      "Support education, health, workforce, food access, or infrastructure.",
      "Collaborate with growers, families, youth, and community organizations.",
      "Help create a replicable model for place-based food system development.",
    ],
  },
  {
    id: "future",
    title: "Future Destination",
    subtitle: "Agritourism and family experiences",
    image: "/FutureDestination.jpg",
    deep: true,
    text: "The long-term vision includes agritourism, family camping, educational experiences, an 18-hole mini-golf course, food education, children’s activities, value-added products, and destination experiences that reconnect people to land, food, and community.",
  },
  {
    id: "closing",
    title: "Thank You",
    subtitle: "Help us grow the ecosystem together",
    image: "/GrowArea2.jpg",
    deep: true,
    closing: true,
    text: "Thank you for experiencing the Bronson Family Farm ecosystem
